"""
Tests for the public ``add_segmentation_derivative`` ingestion API
(``nidm.linkml.experiment.derivatives``).

These prove the FSL/FS/ANTs ingesters get a derivative model identical to
``csv2nidm -derivative``:

  * ``test_standalone_emits_correct_model`` -- a standalone graph carries
    exactly one Derivative / DerivativeObject (typed DerivativeCollection),
    one SoftwareAgent, cmdline/platform on the activity, a Person with
    ndar:src_subject_id, and the measure values on the DerivativeObject.
  * ``test_add_to_existing_attaches_to_person`` -- appending to an
    existing NIDM file wires the subject association to the EXISTING
    Person (no duplicate minted).
  * ``test_cross_graph_join`` -- a standalone derivative graph + a
    separate experiment graph, loaded together, join the measure back to
    the experiment subject via ndar:src_subject_id.
  * ``test_leading_zero_join`` -- the same join tolerates zero-padding
    differences ("0051456" vs "51456"), mirroring the query layer.
"""
from __future__ import annotations
from pathlib import Path
from rdflib import Graph, Literal, URIRef
from rdflib.namespace import RDF, RDFS
from nidm.linkml.core.namespaces import DCT, DCTYPES, NDAR, NIDM, PROV, SIO
from nidm.linkml.experiment import Person, Project
from nidm.linkml.experiment.derivatives import add_segmentation_derivative

# InterLex URIs the GetBrainVolumes join keys on (volume measure + scalar
# datum type).
ILX_VOLUME = URIRef("http://uri.interlex.org/base/ilx_0112559")
ILX_SCALAR = URIRef("http://uri.interlex.org/base/ilx_0738276")

SOFTWARE_URL = "http://surfer.nmr.mgh.harvard.edu/"

SOFTWARE_METADATA = {
    "title": "FreeSurfer",
    "description": "Cortical reconstruction and volumetric segmentation",
    "version": "7.4.1",
    "url": SOFTWARE_URL,
    "cmdline": "recon-all -subjid sub-01 -all",
    "platform": "Linux-5.15.0-x86_64",
}


def _build_cde(measures: dict) -> Graph:
    """Build a minimal CDE graph for *measures* mirroring a real fs/fsl/ants
    CDE: each data element is a ``nidm:DataElement`` carrying an
    ``nidm:sourceVariable`` (what ``add_attributes_with_cde`` matches on)
    plus the ``rdfs:label`` / ``nidm:measureOf`` / ``nidm:datumType`` that
    ``GetBrainVolumes`` joins against.  Returns ``(graph)``; the CDE URIs
    live in the software's namespace, as csv2nidm mints them."""
    cde = Graph()
    for variable in measures:
        cde_uri = URIRef(SOFTWARE_URL + variable)
        cde.add((cde_uri, RDF.type, NIDM["DataElement"]))
        cde.add((cde_uri, NIDM["sourceVariable"], Literal(variable)))
        cde.add((cde_uri, RDFS.label, Literal(variable)))
        cde.add((cde_uri, NIDM["measureOf"], ILX_VOLUME))
        cde.add((cde_uri, NIDM["datumType"], ILX_SCALAR))
    return cde


def _one(subjects) -> URIRef:
    """Return the single element of *subjects*, asserting there is exactly one."""
    items = list(subjects)
    assert len(items) == 1, f"expected exactly one, got {len(items)}: {items}"
    return items[0]


# ---------------------------------------------------------------------------
# 1. Standalone graph model
# ---------------------------------------------------------------------------


def test_standalone_emits_correct_model(tmp_path: Path):
    subject_id = "0050002"
    measures = {
        "Left-Hippocampus": 3500.0,
        "Right-Hippocampus": 3600.0,
        "BrainSegVol": 1200000,
    }
    cde = _build_cde(measures)

    out = tmp_path / "seg.ttl"
    graph = add_segmentation_derivative(
        subject_id=subject_id,
        software_metadata=SOFTWARE_METADATA,
        measures=measures,
        cde=cde,
        nidm_file=None,
        source_url="http://example.org/derivatives/sub-01/stats",
        output_file=str(out),
    )

    # Exactly one Derivative activity.
    der = _one(graph.subjects(RDF.type, NIDM["Derivative"]))

    # Exactly one DerivativeObject, also typed nidm:DerivativeCollection.
    der_obj = _one(graph.subjects(RDF.type, NIDM["DerivativeObject"]))
    assert (der_obj, RDF.type, NIDM["DerivativeCollection"]) in graph
    # The object was generated by the derivative activity.
    assert (der_obj, PROV.wasGeneratedBy, der) in graph

    # Exactly one SoftwareAgent carrying title / version / url.
    agent = _one(graph.subjects(RDF.type, NIDM["SoftwareAgent"]))
    assert (agent, DCTYPES.title, Literal("FreeSurfer")) in graph
    assert (agent, DCT.hasVersion, Literal("7.4.1")) in graph
    assert (agent, SIO.URL, Literal(SOFTWARE_URL)) in graph

    # cmdline + platform on the Derivative ACTIVITY, keyed by software url.
    assert (
        der,
        URIRef(SOFTWARE_URL + "cmdline"),
        Literal(SOFTWARE_METADATA["cmdline"]),
    ) in graph
    assert (
        der,
        URIRef(SOFTWARE_URL + "platform"),
        Literal(SOFTWARE_METADATA["platform"]),
    ) in graph

    # A Person carrying ndar:src_subject_id == subject_id.
    person = _one(graph.subjects(RDF.type, PROV.Person))
    assert (person, NDAR["src_subject_id"], Literal(subject_id)) in graph

    # The subject association links the derivative to that Person with role
    # sio:Subject.
    subj_agents = set()
    for assoc in graph.objects(der, PROV.qualifiedAssociation):
        if SIO.Subject in set(graph.objects(assoc, PROV.hadRole)):
            subj_agents.update(graph.objects(assoc, PROV.agent))
    assert person in subj_agents

    # The measure values are attached to the DerivativeObject via the CDE URIs.
    for variable, value in measures.items():
        cde_uri = URIRef(SOFTWARE_URL + variable)
        obj = graph.value(subject=der_obj, predicate=cde_uri)
        assert obj is not None, f"missing measure {variable}"
        assert float(obj.toPython()) == float(value)

    # source_url landed as a prov:Location URIRef (resource, not literal).
    loc = graph.value(subject=der_obj, predicate=PROV.Location)
    assert isinstance(loc, URIRef)

    # File was serialized.
    assert out.exists()


# ---------------------------------------------------------------------------
# 2. Add to existing NIDM file -> attaches to the existing Person
# ---------------------------------------------------------------------------


def test_add_to_existing_attaches_to_person(tmp_path: Path):
    # Build a tiny existing NIDM file: Project + Person "01".
    exp = Project(title="tiny experiment")
    existing_person = Person(exp, subject_id="01")
    orig_person_uri = URIRef(str(existing_person.identifier))
    existing_file = tmp_path / "experiment.ttl"
    exp.write(existing_file)

    measures = {"BrainSegVol": 1234567}
    cde = _build_cde(measures)

    graph = add_segmentation_derivative(
        subject_id="01",
        software_metadata=SOFTWARE_METADATA,
        measures=measures,
        cde=cde,
        nidm_file=str(existing_file),
    )

    # No duplicate Person minted -- still exactly one, and it's the original.
    persons = list(graph.subjects(RDF.type, PROV.Person))
    assert persons == [orig_person_uri]

    # The derivative's subject association points at the EXISTING Person.
    der = _one(graph.subjects(RDF.type, NIDM["Derivative"]))
    subj_agents = set()
    for assoc in graph.objects(der, PROV.qualifiedAssociation):
        if SIO.Subject in set(graph.objects(assoc, PROV.hadRole)):
            subj_agents.update(graph.objects(assoc, PROV.agent))
    assert orig_person_uri in subj_agents


# ---------------------------------------------------------------------------
# 3. Cross-graph join (uber-graph query works across files)
# ---------------------------------------------------------------------------

# A predicate that lives ONLY in the experiment graph, so a query that
# returns it proves the derivative measure joined to the experiment subject.
AGE_AT_SCAN = NIDM["ageAtScan"]

# Join derivative volumes back to the experiment subject via
# ndar:src_subject_id, requiring the experiment-only ?age so a returned row
# can only come from BOTH files.
_JOIN_QUERY = """
    PREFIX prov: <http://www.w3.org/ns/prov#>
    PREFIX ndar: <https://ndar.nih.gov/api/datadictionary/v2/dataelement/>
    PREFIX nidm: <http://purl.org/nidash/nidm#>
    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

    SELECT DISTINCT ?ID ?volume ?age WHERE {
        ?der_act a nidm:Derivative ;
                 prov:qualifiedAssociation [ prov:agent ?subj ] .
        ?subj a prov:Person ;
              ndar:src_subject_id ?derID .
        ?der_obj prov:wasGeneratedBy ?der_act ;
                 ?measure ?volume .
        ?measure a/rdfs:subClassOf* nidm:DataElement ;
                 nidm:measureOf <http://uri.interlex.org/base/ilx_0112559> ;
                 nidm:datumType <http://uri.interlex.org/base/ilx_0738276> .
        ?exp_person a prov:Person ;
                    ndar:src_subject_id ?ID ;
                    nidm:ageAtScan ?age .
        FILTER( REPLACE(STR(?derID), "^0+", "") = REPLACE(STR(?ID), "^0+", "") )
    }
"""


def _experiment_graph(subject_id: str, age: int) -> Graph:
    """A separate experiment graph: Project + Person(subject_id) carrying an
    experiment-only nidm:ageAtScan (used to prove the cross-file join)."""
    exp = Project(title="experiment")
    person = Person(exp, subject_id=subject_id)
    exp.graph.add((person.identifier, AGE_AT_SCAN, Literal(age)))
    return exp.graph


def _uber_graph(derivative_graph: Graph, experiment_graph: Graph) -> Graph:
    """Load both graphs into one rdflib.Graph (as a triplestore would)."""
    uber = Graph()
    uber.parse(data=derivative_graph.serialize(format="turtle"), format="turtle")
    uber.parse(data=experiment_graph.serialize(format="turtle"), format="turtle")
    return uber


def test_cross_graph_join():
    measures = {"BrainSegVol": 1200000}
    cde = _build_cde(measures)

    derivative_graph = add_segmentation_derivative(
        subject_id="01",
        software_metadata=SOFTWARE_METADATA,
        measures=measures,
        cde=cde,
        nidm_file=None,
    )
    experiment_graph = _experiment_graph(subject_id="01", age=42)

    uber = _uber_graph(derivative_graph, experiment_graph)
    rows = list(uber.query(_JOIN_QUERY))

    assert rows, "cross-graph join returned no rows"
    ids = {str(r["ID"]) for r in rows}
    ages = {int(r["age"]) for r in rows}
    volumes = {int(r["volume"]) for r in rows}
    assert ids == {"01"}
    assert ages == {42}
    assert 1200000 in volumes


# ---------------------------------------------------------------------------
# 4. Leading-zero-tolerant cross-graph join
# ---------------------------------------------------------------------------


def test_leading_zero_join():
    measures = {"BrainSegVol": 999999}
    cde = _build_cde(measures)

    # Derivative subject is zero-padded; experiment subject is not.
    derivative_graph = add_segmentation_derivative(
        subject_id="0051456",
        software_metadata=SOFTWARE_METADATA,
        measures=measures,
        cde=cde,
        nidm_file=None,
    )
    experiment_graph = _experiment_graph(subject_id="51456", age=30)

    uber = _uber_graph(derivative_graph, experiment_graph)
    rows = list(uber.query(_JOIN_QUERY))

    assert rows, "leading-zero join returned no rows"
    ids = {str(r["ID"]) for r in rows}
    volumes = {int(r["volume"]) for r in rows}
    # The experiment subject id (un-padded) is what comes back.
    assert ids == {"51456"}
    assert 999999 in volumes


# ---------------------------------------------------------------------------
# 5. GetBrainVolumes (`pynidm query -bv`) tool binding
# ---------------------------------------------------------------------------
#
# GetBrainVolumes finds the producing tool via
#   prov:qualifiedAssociation [prov:agent [nidm:NIDM_0000164 ?tool]]
# i.e. nidm:NIDM_0000164 must be a PREDICATE on the SoftwareAgent (as in the
# ds002411 FreeSurfer graph: `nidm:NIDM_0000164 fs:`), NOT merely an
# association hadRole.  Without it the derivative is invisible to -bv.

# The exact tool-binding clause GetBrainVolumes uses, applied against the
# derivative's own subject Person (standalone graph carries ndar:src_subject_id).
_GBV_QUERY = """
    prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    prefix prov: <http://www.w3.org/ns/prov#>
    prefix ndar: <https://ndar.nih.gov/api/datadictionary/v2/dataelement/>
    prefix nidm: <http://purl.org/nidash/nidm#>
    prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

    select distinct ?ID ?tool ?softwareLabel ?volume where {
        ?tool_act a prov:Activity ;
                  prov:qualifiedAssociation [prov:agent [nidm:NIDM_0000164 ?tool]] .
        ?tool_act prov:qualifiedAssociation [prov:agent [ndar:src_subject_id ?ID]] .
        ?tool_entity prov:wasGeneratedBy ?tool_act ;
                     ?measure ?volume .
        ?measure a/rdfs:subClassOf* nidm:DataElement ;
                 rdfs:label ?softwareLabel ;
                 nidm:measureOf <http://uri.interlex.org/base/ilx_0112559> ;
                 nidm:datumType <http://uri.interlex.org/base/ilx_0738276> .
    }
"""


def test_software_agent_carries_tool_binding():
    """The SoftwareAgent must carry `nidm:NIDM_0000164 <tool-uri>` as a
    predicate (not just an association role) so GetBrainVolumes can bind ?tool."""
    measures = {"BrainSegVol": 1200000}
    graph = add_segmentation_derivative(
        subject_id="0050002",
        software_metadata=SOFTWARE_METADATA,
        measures=measures,
        cde=_build_cde(measures),
        nidm_file=None,
    )
    agent = _one(graph.subjects(RDF.type, NIDM["SoftwareAgent"]))
    assert (agent, NIDM["NIDM_0000164"], URIRef(SOFTWARE_URL)) in graph


def test_getbrainvolumes_pattern_returns_tool_and_volume():
    """The full GetBrainVolumes tool-binding pattern resolves against a
    standalone derivative graph: ?tool, ?ID and ?volume all bind."""
    measures = {"Left-Hippocampus": 3500.0, "BrainSegVol": 1200000}
    graph = add_segmentation_derivative(
        subject_id="0050002",
        software_metadata=SOFTWARE_METADATA,
        measures=measures,
        cde=_build_cde(measures),
        nidm_file=None,
    )
    rows = list(graph.query(_GBV_QUERY))
    assert rows, "GetBrainVolumes tool-binding pattern returned no rows"
    tools = {str(r["tool"]) for r in rows}
    ids = {str(r["ID"]) for r in rows}
    volumes = {float(r["volume"]) for r in rows}
    assert tools == {SOFTWARE_URL}
    assert ids == {"0050002"}
    assert 1200000 in volumes


def test_merge_cde_false_omits_cde_definitions():
    """merge_cde=False still attaches values via the CDE URI predicate, but
    does NOT copy the CDE definition triples into the output graph."""
    measures = {"BrainSegVol": 1200000}
    cde = _build_cde(measures)
    graph = add_segmentation_derivative(
        subject_id="01",
        software_metadata=SOFTWARE_METADATA,
        measures=measures,
        cde=cde,
        nidm_file=None,
        merge_cde=False,
    )
    cde_uri = URIRef(SOFTWARE_URL + "BrainSegVol")
    der_obj = _one(graph.subjects(RDF.type, NIDM["DerivativeObject"]))
    # value still attached using the CDE URI as predicate
    assert graph.value(subject=der_obj, predicate=cde_uri) is not None
    # but the CDE DEFINITION triples are absent (written separately)
    assert (cde_uri, NIDM["measureOf"], ILX_VOLUME) not in graph
    assert (cde_uri, RDF.type, NIDM["DataElement"]) not in graph


def test_getbrainvolumes_end_to_end(tmp_path: Path):
    """Serialize a standalone derivative and run the REAL GetBrainVolumes
    query function over the file -- the -bv command path."""
    from nidm.linkml.experiment.query import GetBrainVolumes

    measures = {"BrainSegVol": 1200000}
    out = tmp_path / "seg.ttl"
    add_segmentation_derivative(
        subject_id="0050002",
        software_metadata=SOFTWARE_METADATA,
        measures=measures,
        cde=_build_cde(measures),
        nidm_file=None,
        output_file=str(out),
    )
    df = GetBrainVolumes(str(out))
    assert df is not None and len(df) >= 1, "GetBrainVolumes returned no rows"
    # tool and volume made it into the dataframe
    joined = " ".join(str(v) for v in df.to_numpy().flatten())
    assert SOFTWARE_URL in joined
    assert "1200000" in joined
